# Generated by Django 5.0.4 on 2024-07-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0002_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
