# Generated by Django 5.0.4 on 2024-07-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0003_usuario_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
