# Generated by Django 5.0.4 on 2024-07-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0005_alter_usuario_email_alter_usuario_id_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
