# Generated by Django 5.0.4 on 2024-07-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0006_remove_usuario_last_login_remove_usuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
