# Generated by Django 4.1.2 on 2024-07-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0007_remove_usuario_activo_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='isbn',
            new_name='id_libro',
        ),
    ]
