# Generated by Django 5.0.4 on 2024-07-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0008_mensajeforo_mensaje_padre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='isbn',
            new_name='id_libro',
        ),
    ]
